version: "3.7"

services:
  api-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-tests
    volumes:
      - ./:/usr/workspace
    working_dir: /usr/workspace
    command: /bin/sh -c "pytest test_cases_api.py --alluredir=allure-results -v"

  report:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: allure-report
    volumes:
      - ./:/usr/workspace
    working_dir: /usr/workspace
    command: /bin/sh -c "if [ -d allure-results ] && [ \"$(ls -A allure-results)\" ]; then allure generate allure-results --clean -o allure-report; else echo 'No results found, skipping report generation'; exit 1; fi"
    depends_on:
      - api-tests
