version: "3.7"

services:
  api-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-tests
    volumes:
      - ./allure-results:/usr/workspace/allure-results
    working_dir: /usr/workspace
    command: /bin/sh -c "pytest -sv --alluredir=allure-results"

  report:
    image: frankescobar/allure-docker-service
    container_name: allure-report
    volumes:
      - ./allure-results:/app/allure-results
      - ./allure-report:/app/allure-report
    working_dir: /app
    command: /bin/sh -c "allure generate allure-results --clean -o allure-report"
    depends_on:
      - api-tests
