version: "3.7"

services:
  api-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-tests
    volumes:
      - ./:/usr/workspace
    working_dir: /usr/workspace
    command: /bin/sh -c "pytest -sv --alluredir=allure-results"

  report:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: allure-report
    volumes:
      - ./:/usr/workspace
    working_dir: /usr/workspace
    command: /bin/sh -c "allure generate allure-results --clean -o allure-report"
    depends_on:
      - api-tests
