name: API Tests

on:
  workflow_dispatch:
    inputs:
      STAGE:
        description: "Test environment"
        required: true
        default: "prod"
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run API tests
        run: docker compose up --abort-on-container-exit --exit-code-from api-tests

      - name: Generate Allure report
        run: docker compose run --rm report

      - name: Check Allure report folder
        run: |
          if [ ! -d allure-report ] || [ -z "$(ls -A allure-report)" ]; then
            echo "No Allure report found, skipping deploy."
            exit 1
          fi

      - name: Deploy Allure Report to GitHub Pages
        if: success()
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true

      - name: Clean up containers
        run: docker compose down
